package com.dashboard.entity;

import java.util.ArrayList;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "user")
public class User {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String user_id;

	@DynamoDBAttribute
	private String user_name;
	@DynamoDBAttribute
	private int num_courses;

	@DynamoDBAttribute
	private String email_id;

	@DynamoDBAttribute
	private ArrayList<CourseDocument> course_document;

	public User() {
		super();
	}

	public User(String user_id, String user_name, int num_courses, String email_id,
			ArrayList<CourseDocument> course_document) {
		super();
		this.user_id = user_id;
		this.user_name = user_name;
		this.num_courses = num_courses;
		this.email_id = email_id;
		this.course_document = course_document;
	}

	public String getUser_id() {
		return user_id;
	}

	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}

	public String getUser_name() {
		return user_name;
	}

	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}

	public ArrayList<CourseDocument> getCourse_document() {
		return course_document;
	}

	public void setCourse_document(ArrayList<CourseDocument> course_document) {
		this.course_document = course_document;
	}

	public int getNum_courses() {
		return num_courses;
	}

	public void setNum_courses(int i) {
		this.num_courses = i;
	}

	public String getEmail_id() {
		return email_id;
	}

	public void setEmail_id(String email_id) {
		this.email_id = email_id;
	}

}
